apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvo-txtfolder
  namespace: common-words
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/seagate/data/common-words/txtfolder"
