apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claimname-txtfolder
  namespace: common-words
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
